[tool.poetry]
name = "pySigma"
version = "0.1.0"
license = "LGPL-2.1-only"
description = "Sigma rule processing and conversion tools"
authors = ["Thomas Patzke <thomas@patzke.org>"]
readme = "README.md"
repository = "https://github.com/SigmaHQ/pySigma"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Security"
]
packages = [
    { include = "sigma" }
]

[tool.poetry.scripts]
sigma-converter = "sigma.tools.converter:main"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.3.1"
pyparsing = "^2.4.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-mypy = "^0.6.2"
pylint = "^2.6.0"
rope = "^0.18.0"
Sphinx = "^4.2.0"

[build-system]
requires = ["poetry>=1.1.2"]
build-backend = "poetry.masonry.api"

[tool.pytest.ini_options]
addopts = "--cov=sigma --cov-report term --cov-report xml:cov.xml -vv"